# Generated by Django 2.2.7 on 2019-11-25 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mperson1', to=settings.AUTH_USER_MODEL)),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mperson2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
