# Generated by Django 2.2.7 on 2019-11-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_auto_20191122_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
