# Generated by Django 2.2.7 on 2019-11-24 07:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitwise', '0002_auto_20191123_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_transaction_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('tag', models.CharField(choices=[('mv', 'Movies'), ('fd', 'Food'), ('tr', 'Travel'), ('ee', 'Electronics'), ('md', 'Medical'), ('sp', 'Shopping'), ('sv', 'Services'), ('ot', 'Others')], max_length=2)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='splitwise.Group')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
