# Generated by Django 2.2.7 on 2019-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSL', '0002_friend_who_owes_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='who_owes_who',
            field=models.CharField(choices=[('You owe them', 'You owe them'), ('They owe you', 'They owe you')], default='You owe them', max_length=20),
        ),
        migrations.AlterField(
            model_name='friend',
            name='money_owed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='money_owed',
            field=models.IntegerField(default=0),
        ),
    ]
