# Generated by Django 2.2.7 on 2019-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSL', '0003_auto_20191106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='who_owes_who',
            field=models.CharField(choices=[('You owe them', 'You owe them'), ('They owe you', 'They owe you')], default='They owe you', max_length=20),
        ),
    ]
